name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build and deploy
        run: |
          JEKYLL_ENV=production bundle exec jekyll build --destination ./_site
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          touch ./_site/.nojekyll
          git add .
          git commit -m "Deploying to GitHub Pages"
          git push origin main:gh-pages  # Change 'main' to your source branch
